UPDATE CLIENTE 
SET COMENTARIO = 'NO APLICABLE PARA PRESTAMO'
WHERE CLIENTE_ID = 1;

UPDATE CLIENTE 
SET COMENTARIO = 'APLICABLE PARA PRESTAMO'
WHERE CLIENTE_ID = 2;

UPDATE CLIENTE 
SET COMENTARIO = 'APLICABLE PARA PRESTAMO'
WHERE CLIENTE_ID = 3;
